# Generated by Django 5.0.4 on 2024-04-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='codigo_curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
